//! Generated by scripts/emit_str_ops.py from std/str_ops.dl7. Do not edit.
use crate::{StrKind, StrOut, StrVal};
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum StrOp {
    Len,
    Lower,
    Upper,
    Lcfirst,
    Ucfirst,
    Trim,
    StripPrefix,
    StripSuffix,
    Replace,
    Split,
    ToStr,
    ToInt,
    StartsWith,
    Contains,
    Snake,
    Camel,
    Pascal,
    Kebab,
}

impl StrOp {
    pub const ALL: &'static [StrOp] = &[
        StrOp::Len,
        StrOp::Lower,
        StrOp::Upper,
        StrOp::Lcfirst,
        StrOp::Ucfirst,
        StrOp::Trim,
        StrOp::StripPrefix,
        StrOp::StripSuffix,
        StrOp::Replace,
        StrOp::Split,
        StrOp::ToStr,
        StrOp::ToInt,
        StrOp::StartsWith,
        StrOp::Contains,
        StrOp::Snake,
        StrOp::Camel,
        StrOp::Pascal,
        StrOp::Kebab,
    ];

    pub fn name(self) -> &'static str {
        match self {
            StrOp::Len => "str.len",
            StrOp::Lower => "str.lower",
            StrOp::Upper => "str.upper",
            StrOp::Lcfirst => "str.lcfirst",
            StrOp::Ucfirst => "str.ucfirst",
            StrOp::Trim => "str.trim",
            StrOp::StripPrefix => "str.strip_prefix",
            StrOp::StripSuffix => "str.strip_suffix",
            StrOp::Replace => "str.replace",
            StrOp::Split => "str.split",
            StrOp::ToStr => "int.to_str",
            StrOp::ToInt => "str.to_int",
            StrOp::StartsWith => "str.starts_with",
            StrOp::Contains => "str.contains",
            StrOp::Snake => "str.snake",
            StrOp::Camel => "str.camel",
            StrOp::Pascal => "str.pascal",
            StrOp::Kebab => "str.kebab",
        }
    }

    pub fn from_name(name: &str) -> Option<StrOp> {
        match name {
            "str.len" => Some(StrOp::Len),
            "str.lower" => Some(StrOp::Lower),
            "str.upper" => Some(StrOp::Upper),
            "str.lcfirst" => Some(StrOp::Lcfirst),
            "str.ucfirst" => Some(StrOp::Ucfirst),
            "str.trim" => Some(StrOp::Trim),
            "str.strip_prefix" => Some(StrOp::StripPrefix),
            "str.strip_suffix" => Some(StrOp::StripSuffix),
            "str.replace" => Some(StrOp::Replace),
            "str.split" => Some(StrOp::Split),
            "int.to_str" => Some(StrOp::ToStr),
            "str.to_int" => Some(StrOp::ToInt),
            "str.starts_with" => Some(StrOp::StartsWith),
            "str.contains" => Some(StrOp::Contains),
            "str.snake" => Some(StrOp::Snake),
            "str.camel" => Some(StrOp::Camel),
            "str.pascal" => Some(StrOp::Pascal),
            "str.kebab" => Some(StrOp::Kebab),
            _ => None,
        }
    }

    pub fn args(self) -> &'static [StrKind] {
        match self {
            StrOp::Len => &[StrKind::Text, ],
            StrOp::Lower => &[StrKind::Text, ],
            StrOp::Upper => &[StrKind::Text, ],
            StrOp::Lcfirst => &[StrKind::Text, ],
            StrOp::Ucfirst => &[StrKind::Text, ],
            StrOp::Trim => &[StrKind::Text, ],
            StrOp::StripPrefix => &[StrKind::Text, StrKind::Text, ],
            StrOp::StripSuffix => &[StrKind::Text, StrKind::Text, ],
            StrOp::Replace => &[StrKind::Text, StrKind::Text, StrKind::Text, ],
            StrOp::Split => &[StrKind::Text, StrKind::Text, StrKind::Int, ],
            StrOp::ToStr => &[StrKind::Int, ],
            StrOp::ToInt => &[StrKind::Text, ],
            StrOp::StartsWith => &[StrKind::Text, StrKind::Text, ],
            StrOp::Contains => &[StrKind::Text, StrKind::Text, ],
            StrOp::Snake => &[StrKind::Text, ],
            StrOp::Camel => &[StrKind::Text, ],
            StrOp::Pascal => &[StrKind::Text, ],
            StrOp::Kebab => &[StrKind::Text, ],
        }
    }

    pub fn out(self) -> Option<StrKind> {
        match self {
            StrOp::Len => Some(StrKind::Int),
            StrOp::Lower => Some(StrKind::Text),
            StrOp::Upper => Some(StrKind::Text),
            StrOp::Lcfirst => Some(StrKind::Text),
            StrOp::Ucfirst => Some(StrKind::Text),
            StrOp::Trim => Some(StrKind::Text),
            StrOp::StripPrefix => Some(StrKind::Text),
            StrOp::StripSuffix => Some(StrKind::Text),
            StrOp::Replace => Some(StrKind::Text),
            StrOp::Split => Some(StrKind::Text),
            StrOp::ToStr => Some(StrKind::Text),
            StrOp::ToInt => Some(StrKind::Int),
            StrOp::StartsWith => None,
            StrOp::Contains => None,
            StrOp::Snake => Some(StrKind::Text),
            StrOp::Camel => Some(StrKind::Text),
            StrOp::Pascal => Some(StrKind::Text),
            StrOp::Kebab => Some(StrKind::Text),
        }
    }

    pub fn apply(self, args: &[StrVal]) -> Option<StrOut> {
        use crate::{int, text};
        use StrOut::{Holds, Int, Text};
        match self {
            StrOp::Len => {
                let a0 = text(args, 0)?;
                Some(Int(a0.chars().count() as i64))
            }
            StrOp::Lower => {
                let a0 = text(args, 0)?;
                Some(Text(a0.to_lowercase()))
            }
            StrOp::Upper => {
                let a0 = text(args, 0)?;
                Some(Text(a0.to_uppercase()))
            }
            StrOp::Lcfirst => {
                let a0 = text(args, 0)?;
                Some(Text({ let mut chars = a0.chars(); chars.next().map(|first| first.to_lowercase().chain(chars).collect::<String>()).unwrap_or_default() }))
            }
            StrOp::Ucfirst => {
                let a0 = text(args, 0)?;
                Some(Text({ let mut chars = a0.chars(); chars.next().map(|first| first.to_uppercase().chain(chars).collect::<String>()).unwrap_or_default() }))
            }
            StrOp::Trim => {
                let a0 = text(args, 0)?;
                Some(Text(a0.trim().to_string()))
            }
            StrOp::StripPrefix => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                Some(Text(a0.strip_prefix(a1).unwrap_or(a0).to_string()))
            }
            StrOp::StripSuffix => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                Some(Text(a0.strip_suffix(a1).unwrap_or(a0).to_string()))
            }
            StrOp::Replace => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                let a2 = text(args, 2)?;
                Some(Text(a0.replace(a1, a2)))
            }
            StrOp::Split => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                let a2 = int(args, 2)?;
                { let parts: Vec<&str> = a0.split(a1).collect(); let at = if a2 < 0 { a2.checked_add(parts.len() as i64)? } else { a2 }; parts.get(usize::try_from(at).ok()?).map(|part| Text(part.to_string())) }
            }
            StrOp::ToStr => {
                let a0 = int(args, 0)?;
                Some(Text(a0.to_string()))
            }
            StrOp::ToInt => {
                let a0 = text(args, 0)?;
                a0.parse::<i64>().ok().map(Int)
            }
            StrOp::StartsWith => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                a0.starts_with(a1).then_some(Holds)
            }
            StrOp::Contains => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                a0.contains(a1).then_some(Holds)
            }
            StrOp::Snake => {
                let a0 = text(args, 0)?;
                Some(Text(heck::ToSnakeCase::to_snake_case(a0)))
            }
            StrOp::Camel => {
                let a0 = text(args, 0)?;
                Some(Text(heck::ToLowerCamelCase::to_lower_camel_case(a0)))
            }
            StrOp::Pascal => {
                let a0 = text(args, 0)?;
                Some(Text(heck::ToUpperCamelCase::to_upper_camel_case(a0)))
            }
            StrOp::Kebab => {
                let a0 = text(args, 0)?;
                Some(Text(heck::ToKebabCase::to_kebab_case(a0)))
            }
        }
    }
}
