//! Generated by scripts/emit_str_ops.py from std/str_ops.dl7. Do not edit.
use crate::{StrKind, StrOut, StrVal};
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum StrOp {
    Len,
    Lower,
    Upper,
    Lcfirst,
    Ucfirst,
    Trim,
    StripPrefix,
    StripSuffix,
    Replace,
    Split,
}

impl StrOp {
    pub const ALL: &'static [StrOp] = &[
        StrOp::Len,
        StrOp::Lower,
        StrOp::Upper,
        StrOp::Lcfirst,
        StrOp::Ucfirst,
        StrOp::Trim,
        StrOp::StripPrefix,
        StrOp::StripSuffix,
        StrOp::Replace,
        StrOp::Split,
    ];

    pub fn name(self) -> &'static str {
        match self {
            StrOp::Len => "len",
            StrOp::Lower => "lower",
            StrOp::Upper => "upper",
            StrOp::Lcfirst => "lcfirst",
            StrOp::Ucfirst => "ucfirst",
            StrOp::Trim => "trim",
            StrOp::StripPrefix => "strip_prefix",
            StrOp::StripSuffix => "strip_suffix",
            StrOp::Replace => "replace",
            StrOp::Split => "split",
        }
    }

    pub fn from_name(name: &str) -> Option<StrOp> {
        match name {
            "len" => Some(StrOp::Len),
            "lower" => Some(StrOp::Lower),
            "upper" => Some(StrOp::Upper),
            "lcfirst" => Some(StrOp::Lcfirst),
            "ucfirst" => Some(StrOp::Ucfirst),
            "trim" => Some(StrOp::Trim),
            "strip_prefix" => Some(StrOp::StripPrefix),
            "strip_suffix" => Some(StrOp::StripSuffix),
            "replace" => Some(StrOp::Replace),
            "split" => Some(StrOp::Split),
            _ => None,
        }
    }

    pub fn args(self) -> &'static [StrKind] {
        match self {
            StrOp::Len => &[StrKind::Text, ],
            StrOp::Lower => &[StrKind::Text, ],
            StrOp::Upper => &[StrKind::Text, ],
            StrOp::Lcfirst => &[StrKind::Text, ],
            StrOp::Ucfirst => &[StrKind::Text, ],
            StrOp::Trim => &[StrKind::Text, ],
            StrOp::StripPrefix => &[StrKind::Text, StrKind::Text, ],
            StrOp::StripSuffix => &[StrKind::Text, StrKind::Text, ],
            StrOp::Replace => &[StrKind::Text, StrKind::Text, StrKind::Text, ],
            StrOp::Split => &[StrKind::Text, StrKind::Text, StrKind::Int, ],
        }
    }

    pub fn out(self) -> StrKind {
        match self {
            StrOp::Len => StrKind::Int,
            StrOp::Lower => StrKind::Text,
            StrOp::Upper => StrKind::Text,
            StrOp::Lcfirst => StrKind::Text,
            StrOp::Ucfirst => StrKind::Text,
            StrOp::Trim => StrKind::Text,
            StrOp::StripPrefix => StrKind::Text,
            StrOp::StripSuffix => StrKind::Text,
            StrOp::Replace => StrKind::Text,
            StrOp::Split => StrKind::Text,
        }
    }

    pub fn apply(self, args: &[StrVal]) -> Option<StrOut> {
        use crate::{int, text};
        use StrOut::{Int, Text};
        match self {
            StrOp::Len => {
                let a0 = text(args, 0)?;
                Some(Int(a0.chars().count() as i64))
            }
            StrOp::Lower => {
                let a0 = text(args, 0)?;
                Some(Text(a0.to_lowercase()))
            }
            StrOp::Upper => {
                let a0 = text(args, 0)?;
                Some(Text(a0.to_uppercase()))
            }
            StrOp::Lcfirst => {
                let a0 = text(args, 0)?;
                Some(Text({ let mut chars = a0.chars(); chars.next().map(|first| first.to_lowercase().chain(chars).collect::<String>()).unwrap_or_default() }))
            }
            StrOp::Ucfirst => {
                let a0 = text(args, 0)?;
                Some(Text({ let mut chars = a0.chars(); chars.next().map(|first| first.to_uppercase().chain(chars).collect::<String>()).unwrap_or_default() }))
            }
            StrOp::Trim => {
                let a0 = text(args, 0)?;
                Some(Text(a0.trim().to_string()))
            }
            StrOp::StripPrefix => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                Some(Text(a0.strip_prefix(a1).unwrap_or(a0).to_string()))
            }
            StrOp::StripSuffix => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                Some(Text(a0.strip_suffix(a1).unwrap_or(a0).to_string()))
            }
            StrOp::Replace => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                let a2 = text(args, 2)?;
                Some(Text(a0.replace(a1, a2)))
            }
            StrOp::Split => {
                let a0 = text(args, 0)?;
                let a1 = text(args, 1)?;
                let a2 = int(args, 2)?;
                { let parts: Vec<&str> = a0.split(a1).collect(); let at = if a2 < 0 { a2.checked_add(parts.len() as i64)? } else { a2 }; parts.get(usize::try_from(at).ok()?).map(|part| Text(part.to_string())) }
            }
        }
    }
}
