import { MotionConfig, useReducedMotion } from "motion/react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { Trace } from "./0_trace";
import { HoverStyle, rootHoverHandlers } from "./2_hover";
import { TraceContext } from "./3_Mention";
import { PulseStyle, SPEEDS, useWaveState, WaveContext, type Speed } from "./3a_wave";
import { PlanContext, schedule } from "./3b_schedule";
import { Graph } from "./4_Graph";
import { Answer, Cast, Story } from "./5_Side";
import { Inspector } from "./6_Inspector";
import { Engines } from "./7_Engines";
import { ScenarioTabs, Scrubber, Settings, WaveBar } from "./8_Scrubber";

// Generated by examples/1_trace.rs; inlined into the single-file build.
const modules = import.meta.glob<Trace>("../traces/*.json", { eager: true, import: "default" });
export const traces = Object.values(modules).sort((left, right) => left.scenario.localeCompare(right.scenario, undefined, { numeric: true }));

// Page settings kept across reloads.
const useStored = <T,>(key: string, initial: T, valid: (value: unknown) => boolean) => {
  const [value, setValue] = useState<T>(() => {
    try {
      const raw = localStorage.getItem(key);
      const parsed: unknown = raw === null ? initial : JSON.parse(raw);
      return valid(parsed) ? (parsed as T) : initial;
    } catch {
      return initial;
    }
  });
  useEffect(() => {
    try {
      localStorage.setItem(key, JSON.stringify(value));
    } catch {
      // storage unavailable: the setting lasts for this page only
    }
  }, [key, value]);
  return [value, setValue] as const;
};

type SettingsState = { speed: Speed; setSpeed: (speed: Speed) => void; rowEdges: boolean; setRowEdges: (on: boolean) => void };

// One scenario; remounted per scenario so switching tabs does not animate rows across traces.
const Scenario = ({ trace, header, settings }: { trace: Trace; header: (scrubber: React.ReactNode) => React.ReactNode; settings: SettingsState }) => {
  const [stepIndex, setStepIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const reduced = useReducedMotion() ?? false;
  const wave = useWaveState(trace, stepIndex, settings.speed, reduced);
  const last = trace.steps.length - 1;
  const plan = useMemo(() => schedule(trace, wave), [trace, wave.from, wave.to, wave.depth, wave.max_depth]);
  const waveKeys = useRef({ controls: wave.controls, stops: plan.stops });
  waveKeys.current = { controls: wave.controls, stops: plan.stops };

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "ArrowLeft") setStepIndex((index) => Math.max(0, index - 1));
      if (event.key === "ArrowRight") setStepIndex((index) => Math.min(last, index + 1));
      if (event.key === " ") {
        event.preventDefault();
        if (settings.speed === "step") waveKeys.current.controls.advance(waveKeys.current.stops);
        else waveKeys.current.controls.toggle();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [last, settings.speed]);

  return (
    <TraceContext.Provider value={trace}>
      <WaveContext.Provider value={wave}>
      <PlanContext.Provider value={plan}>
        <PulseStyle trace={trace} />
        {header(
          <>
            <Scrubber
              trace={trace}
              stepIndex={stepIndex}
              onStep={setStepIndex}
              settings={<Settings speed={settings.speed} onSpeed={settings.setSpeed} rowEdges={settings.rowEdges} onRowEdges={settings.setRowEdges} />}
            />
            <WaveBar trace={trace} />
          </>,
        )}
        <main className="grid min-h-0 flex-1 grid-cols-[minmax(240px,1fr)_minmax(360px,2fr)_minmax(300px,1.3fr)] gap-2">
          <aside className="flex min-h-0 flex-col gap-2 overflow-y-auto">
            <Cast />
            <Story />
            <Answer />
          </aside>
          <div className="min-h-0 rounded-lg border border-slate-200 bg-white shadow-sm">
            <Graph trace={trace} selected={selected} onSelect={setSelected} reduced={reduced} rowEdges={settings.rowEdges} />
          </div>
          <aside className="min-h-0 overflow-y-auto">
            <Inspector key={selected ?? "none"} selected={selected} />
          </aside>
        </main>
        <footer className="max-h-[32vh] overflow-y-auto">
          <Engines stepIndex={stepIndex} onStep={setStepIndex} />
        </footer>
      </PlanContext.Provider>
      </WaveContext.Provider>
    </TraceContext.Provider>
  );
};

export const App = () => {
  const [scenario, setScenario] = useState(traces[0]?.scenario ?? "");
  const trace = traces.find((candidate) => candidate.scenario === scenario);
  const [speed, setSpeed] = useStored<Speed>("pokemon-trace-demo.speed", 1, (value) => SPEEDS.includes(value as Speed));
  const [rowEdges, setRowEdges] = useStored("pokemon-trace-demo.row_edges", false, (value) => typeof value === "boolean");

  if (!trace) {
    return (
      <div className="p-8 text-slate-600">
        No traces found in <code>demo/traces/</code>. Generate them with <code>examples/1_trace.rs</code>, then rebuild.
      </div>
    );
  }

  return (
    <MotionConfig reducedMotion="user">
      <HoverStyle />
      <div {...rootHoverHandlers} className="flex h-screen flex-col gap-2 p-3">
        <Scenario
          key={trace.scenario}
          trace={trace}
          settings={{ speed, setSpeed, rowEdges, setRowEdges }}
          header={(scrubber) => (
            <header>
              <ScenarioTabs traces={traces} current={trace.scenario} onPick={setScenario} />
              {scrubber}
            </header>
          )}
        />
      </div>
    </MotionConfig>
  );
};
