#[path = "0a_catalog.rs"]
pub mod catalog;
#[path = "3_extension.rs"]
pub mod extension;
#[path = "0b_relational.rs"]
pub mod relational;
#[path = "0c_compile_from.rs"]
pub mod compile_from;
#[path = "0d_compile_select.rs"]
pub mod compile_select;
#[path = "0e_compile_recursive.rs"]
pub mod compile_recursive;
#[path = "0f_columns.rs"]
pub mod columns;
#[path = "0g_statements.rs"]
pub(crate) mod statements;
#[path = "1a_relational.rs"]
pub mod relational_maintenance;
#[path = "1ab_native_keys.rs"]
pub(crate) mod native_keys;
#[path = "1b_state.rs"]
pub mod relational_state;
#[path = "1c_materialize.rs"]
pub mod relational_materialize;
#[path = "1ca_source_reads.rs"]
pub(crate) mod source_reads;
#[path = "1d_drain.rs"]
pub mod relational_drain;
#[path = "1e_program.rs"]
pub mod relational_program;
#[path = "2a_source_ddl.rs"]
pub mod source_ddl;
#[path = "2_vtab.rs"]
pub mod vtab;
